name:                todo-app
version:             0.1.0.0
github:              "githubuser/todo-app"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/todo-app#readme>

default-extensions:
  - TypeFamilies
  - TypeSynonymInstances
  - FlexibleInstances
  - DeriveGeneric
  - DeriveAnyClass
  - FlexibleContexts
  - OverloadedStrings
  - RecordWildCards
  - StandaloneDeriving
  - DuplicateRecordFields
  - RankNTypes
  - NamedFieldPuns
  - ScopedTypeVariables
  - TypeOperators
  - DataKinds

dependencies:
- base >= 4.7 && < 5
- beam-core
- beam-postgres
- hedis
- servant
- servant-client
- servant-client-core
- servant-server
- http-client
- wai
- warp
- transformers
- text
- aeson
- time
- uuid
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  todo-app-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todo-app

tests:
  todo-app-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - todo-app
